/**
 * EMERGE-X Centralized Demo Data Module
 * 
 * Single source of truth for prototype presentation and offline demonstration.
 * All demo telemetry, emergency info, moving green corridor steps, and junction
 * states are structured here to ensure zero scattered mockup constants across components.
 */

export const DEMO_METADATA = {
  system_name: "EMERGE-X",
  system_subtitle: "Emergency Mobility & Traffic Coordination",
  tagline: "Clearing the way. Saving critical minutes.",
  mode: "DEMO MODE",
  is_simulated: true,
  simulation_label: "SIMULATED TELEMETRY & VIRTUAL CORRIDOR",
  hospital: {
    name: "City General Hospital",
    address: "Central Healthcare Zone, Sector 4",
    triage_readiness: "READY & RESERVED",
    trauma_bay: "Trauma Bay #1 (Level 1 Resus)",
    on_duty_physician: "Dr. Arvind (Emergency Lead)",
    contact: "+91 (080) 4122-9900",
  },
  junctions_info: {
    J1: { name: "Silk Board North", type: "4-Way Major Intersection", cross_streets: "Outer Ring Rd x Hosur Rd", lat: 12.9710, lng: 77.5930 },
    J2: { name: "Koramangala Cross", type: "4-Way High-Volume Node", cross_streets: "100ft Rd x 80ft Rd", lat: 12.9740, lng: 77.5950 },
    J3: { name: "MG Road Entry", type: "3-Way Commercial Node", cross_streets: "MG Rd x Trinity Junction", lat: 12.9770, lng: 77.5970 },
    J4: { name: "Hospital Boulevard", type: "Dedicated Hospital Approach", cross_streets: "Health Complex Blvd", lat: 12.9800, lng: 77.6000 },
    J5: { name: "Express Bypass", type: "Express Bypass Highway", cross_streets: "Inner Ring Rd Bypass", lat: 12.9750, lng: 77.6050 },
  },
};

export const JUNCTION_COORDINATES = {
  J1: { lat: 12.9710, lng: 77.5930, name: "Silk Board North (J1)" },
  J2: { lat: 12.9740, lng: 77.5950, name: "Koramangala Cross (J2)" },
  J3: { lat: 12.9770, lng: 77.5970, name: "MG Road Entry (J3)" },
  J4: { lat: 12.9800, lng: 77.6000, name: "Hospital Boulevard (J4)" },
  J5: { lat: 12.9750, lng: 77.6050, name: "Express Bypass (J5)" },
};

export const HOSPITAL_COORDINATES = {
  lat: 12.9808,
  lng: 77.6006,
  name: "City General Hospital",
};

export const DEMO_SCENARIO_STEPS = [
  {
    step_index: 0,
    step_label: "Step 1 of 3: J2 Active Priority",
    step_summary: "Ambulance approaching J2. Corridor green granted to J2, J3 enters preparation, J1 safe recovery.",
    emergency: {
      emergency_id: "E-001",
      vehicle_id: "AX-01",
      status: "ACTIVE CRITICAL",
      destination: "City General Hospital",
      eta: "8 min",
      eta_seconds: 480,
      severity_tier: "Tier 1 - Immediate Resuscitation",
      patient_summary: "Severe Cardiac Event (En Route)",
      created_at: "Just now (Simulated)",
    },
    telemetry: {
      vehicle_id: "AX-01",
      latitude: 12.9740,
      longitude: 77.5940,
      speed_kmh: 50,
      heading: "ENE (68°)",
      rfid_tag: "E280689420000001",
      gps_quality: "High Fix (8 Satellites)",
      last_update: "just now / simulated",
      data_source: "DEMO TELEMETRY",
    },
    route: ["J1", "J2", "J3", "J4"],
    current_priority_junction: "J2",
    junction_states: {
      J1: "COMPLETED",
      J2: "ACTIVE_PRIORITY",
      J3: "PREPARING",
      J4: "NORMAL",
    },
    priority_command: {
      junction_id: "J2",
      vehicle_id: "AX-01",
      state: "ACTIVE PRIORITY",
      green_corridor_sec: 30,
      max_hold_sec: 45,
      yellow_transition_sec: 3,
      all_red_clearance_sec: 2,
      trip_id: "TRIP-E001-DEMO",
      active_phase: "NORTH-BOUND EMERGENCY CORRIDOR (GREEN)",
      conflicting_phase: "EAST-WEST / CROSS TRAFFIC (LOCKED RED)",
      is_simulated: true,
    },
    secondary_ambulance: {
      vehicle_id: "AX-02",
      emergency_id: "E-002",
      status: "ACTIVE STANDBY",
      priority_status: "STANDBY / EN ROUTE",
      destination: "City General Hospital (Bay 2)",
      eta: "14 min",
      eta_seconds: 840,
      severity_tier: "Tier 2 - Urgent Trauma",
      patient_summary: "Fracture Trauma Stabilized (En Route)",
      latitude: 12.9720,
      longitude: 77.5980,
      speed_kmh: 40,
      heading: "ENE (75°)",
      route: ["J1", "J5", "J4"],
      current_junction: "J1",
      next_junction: "J5",
      data_source: "SIMULATED / DEMO ONLY",
      is_simulated: true,
    },
  },
  {
    step_index: 1,
    step_label: "Step 2 of 3: J3 Active Priority",
    step_summary: "Ambulance cleared J2! Dynamic corridor shifted to J3, J4 begins preparation phase.",
    emergency: {
      emergency_id: "E-001",
      vehicle_id: "AX-01",
      status: "ACTIVE CRITICAL",
      destination: "City General Hospital",
      eta: "5 min",
      eta_seconds: 300,
      severity_tier: "Tier 1 - Immediate Resuscitation",
      patient_summary: "Severe Cardiac Event (En Route)",
      created_at: "3 min ago (Simulated)",
    },
    telemetry: {
      vehicle_id: "AX-01",
      latitude: 12.9785,
      longitude: 77.5990,
      speed_kmh: 55,
      heading: "NE (45°)",
      rfid_tag: "E280689420000001",
      gps_quality: "High Fix (9 Satellites)",
      last_update: "just now / simulated",
      data_source: "DEMO TELEMETRY",
    },
    route: ["J1", "J2", "J3", "J4"],
    current_priority_junction: "J3",
    junction_states: {
      J1: "COMPLETED",
      J2: "COMPLETED",
      J3: "ACTIVE_PRIORITY",
      J4: "PREPARING",
    },
    priority_command: {
      junction_id: "J3",
      vehicle_id: "AX-01",
      state: "ACTIVE PRIORITY",
      green_corridor_sec: 30,
      max_hold_sec: 45,
      yellow_transition_sec: 3,
      all_red_clearance_sec: 2,
      trip_id: "TRIP-E001-DEMO",
      active_phase: "EAST-BOUND EMERGENCY CORRIDOR (GREEN)",
      conflicting_phase: "NORTH-SOUTH CROSS TRAFFIC (LOCKED RED)",
      is_simulated: true,
    },
    secondary_ambulance: {
      vehicle_id: "AX-02",
      emergency_id: "E-002",
      status: "ACTIVE EN ROUTE",
      priority_status: "APPROACHING BYPASS",
      destination: "City General Hospital (Bay 2)",
      eta: "9 min",
      eta_seconds: 540,
      severity_tier: "Tier 2 - Urgent Trauma",
      patient_summary: "Fracture Trauma Stabilized (En Route)",
      latitude: 12.9750,
      longitude: 77.6030,
      speed_kmh: 45,
      heading: "NNE (25°)",
      route: ["J1", "J5", "J4"],
      current_junction: "J5",
      next_junction: "J4",
      data_source: "SIMULATED / DEMO ONLY",
      is_simulated: true,
    },
  },
  {
    step_index: 2,
    step_label: "Step 3 of 3: J4 Active Priority (Hospital Gate)",
    step_summary: "Ambulance approaching final hospital junction J4. Emergency bay doors standing by.",
    emergency: {
      emergency_id: "E-001",
      vehicle_id: "AX-01",
      status: "ACTIVE CRITICAL",
      destination: "City General Hospital",
      eta: "2 min",
      eta_seconds: 120,
      severity_tier: "Tier 1 - Immediate Resuscitation",
      patient_summary: "Severe Cardiac Event (En Route)",
      created_at: "6 min ago (Simulated)",
    },
    telemetry: {
      vehicle_id: "AX-01",
      latitude: 12.9830,
      longitude: 77.6045,
      speed_kmh: 45,
      heading: "N (10°)",
      rfid_tag: "E280689420000001",
      gps_quality: "High Fix (10 Satellites)",
      last_update: "just now / simulated",
      data_source: "DEMO TELEMETRY",
    },
    route: ["J1", "J2", "J3", "J4"],
    current_priority_junction: "J4",
    junction_states: {
      J1: "COMPLETED",
      J2: "COMPLETED",
      J3: "COMPLETED",
      J4: "ACTIVE_PRIORITY",
    },
    priority_command: {
      junction_id: "J4",
      vehicle_id: "AX-01",
      state: "ACTIVE PRIORITY",
      green_corridor_sec: 30,
      max_hold_sec: 45,
      yellow_transition_sec: 3,
      all_red_clearance_sec: 2,
      trip_id: "TRIP-E001-DEMO",
      active_phase: "HOSPITAL INGRESS CORRIDOR (GREEN)",
      conflicting_phase: "PERIMETER ACCESS TRAFFIC (LOCKED RED)",
      is_simulated: true,
    },
    secondary_ambulance: {
      vehicle_id: "AX-02",
      emergency_id: "E-002",
      status: "FINAL APPROACH",
      priority_status: "APPROACHING HOSPITAL",
      destination: "City General Hospital (Bay 2)",
      eta: "4 min",
      eta_seconds: 240,
      severity_tier: "Tier 2 - Urgent Trauma",
      patient_summary: "Fracture Trauma Stabilized (En Route)",
      latitude: 12.9785,
      longitude: 77.6020,
      speed_kmh: 35,
      heading: "NW (315°)",
      route: ["J1", "J5", "J4"],
      current_junction: "J4",
      next_junction: "HOSPITAL",
      data_source: "SIMULATED / DEMO ONLY",
      is_simulated: true,
    },
  },
];

/**
 * Returns the demo state for a given step index (0, 1, or 2).
 */
export function getDemoStep(stepIndex = 0) {
  const safeIndex = ((stepIndex % DEMO_SCENARIO_STEPS.length) + DEMO_SCENARIO_STEPS.length) % DEMO_SCENARIO_STEPS.length;
  return {
    ...DEMO_SCENARIO_STEPS[safeIndex],
    metadata: DEMO_METADATA,
  };
}

export const INITIAL_DEMO_STATE = getDemoStep(0);
